/**
 * lib/permissions2 — Taxonomy quyền nghiệp vụ mới (UPPER_SNAKE), tách theo
 * Clinical / Resource / Finance / Administration / System.
 * Không thay thế hospital.js ROLE_PERMISSIONS (RBAC cũ giữ nguyên chạy song song);
 * module này là lớp enforce chặt cho các API nghiệp vụ mới (encounter, resource,
 * payment, document...). Mọi check quyền mới PHẢI qua can() ở backend/API.
 */
"use strict";

const CLINICAL = [
  "PATIENT_VIEW", "PATIENT_UPDATE", "ENCOUNTER_VIEW", "ENCOUNTER_CREATE",
  "CLINICAL_NOTE_CREATE", "CLINICAL_NOTE_UPDATE",
  "DIAGNOSIS_VIEW", "DIAGNOSIS_UPDATE",
  "ORDER_CREATE", "RESULT_VIEW", "RESULT_VERIFY",
  "PRESCRIPTION_CREATE", "PRESCRIPTION_APPROVE",
];
const RESOURCE = [
  "RESOURCE_VIEW", "RESOURCE_CREATE", "RESOURCE_UPDATE",
  "RESOURCE_REQUEST", "RESOURCE_APPROVE", "RESOURCE_ISSUE",
];
const FINANCE = ["BILL_VIEW", "PAYMENT_CREATE", "PAYMENT_VERIFY", "REFUND_APPROVE"];
const ADMIN_DOC = ["DOCUMENT_CREATE", "DOCUMENT_RECEIVE", "DOCUMENT_PROCESS", "DOCUMENT_APPROVE"];
const SYSTEM = ["USER_CREATE", "ROLE_ASSIGN", "PERMISSION_ASSIGN", "AUDIT_VIEW"];
const CARE_OPS = ["SOS_VIEW", "SOS_UPDATE", "SCHEDULE_VIEW", "SCHEDULE_MANAGE",
  "BHYT_VIEW", "BHYT_VERIFY", "CAPACITY_VIEW", "CAPACITY_MANAGE",
  "HEALTH_DATA_VIEW", "ANOMALY_VIEW", "ANOMALY_REVIEW"];

const ALL = [...CLINICAL, ...RESOURCE, ...FINANCE, ...ADMIN_DOC, ...SYSTEM, ...CARE_OPS];

/* Role (legacy + DEMO1) -> quyền mới. Nguyên tắc §XL giữ nguyên:
 * BS không finance/HR/RBAC; ĐD không chẩn đoán/user-admin; DS không EMR-admin;
 * KT không clinical; IT không sửa bệnh án. */
const ROLE_PERMS2 = {
  CEO: ALL.filter((p) => !["ROLE_ASSIGN", "PERMISSION_ASSIGN"].includes(p)),
  ADMIN: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "RESULT_VIEW", "RESOURCE_VIEW", "RESOURCE_CREATE", "RESOURCE_UPDATE", "RESOURCE_REQUEST",
    "BILL_VIEW", "DOCUMENT_CREATE", "DOCUMENT_RECEIVE", "DOCUMENT_PROCESS",
    "USER_CREATE", "AUDIT_VIEW", "SOS_VIEW", "SOS_UPDATE", "SCHEDULE_VIEW", "SCHEDULE_MANAGE",
    "BHYT_VIEW", "CAPACITY_VIEW", "ANOMALY_VIEW", "HEALTH_DATA_VIEW"],
  HOSPITAL_DIRECTOR: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "DIAGNOSIS_VIEW", "RESULT_VIEW",
    "RESOURCE_VIEW", "RESOURCE_CREATE", "RESOURCE_UPDATE", "RESOURCE_APPROVE", "BILL_VIEW", "PAYMENT_VERIFY", "REFUND_APPROVE",
    "DOCUMENT_APPROVE", "AUDIT_VIEW", "SOS_VIEW", "SCHEDULE_VIEW",
    "BHYT_VIEW", "CAPACITY_VIEW", "CAPACITY_MANAGE", "ANOMALY_VIEW", "ANOMALY_REVIEW", "HEALTH_DATA_VIEW"],
  DEPUTY_DIRECTOR: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "DIAGNOSIS_VIEW", "RESULT_VIEW",
    "RESOURCE_VIEW", "RESOURCE_CREATE", "RESOURCE_UPDATE", "RESOURCE_APPROVE", "BILL_VIEW", "DOCUMENT_APPROVE",
    "SOS_VIEW", "SCHEDULE_VIEW", "BHYT_VIEW", "CAPACITY_VIEW", "ANOMALY_VIEW", "HEALTH_DATA_VIEW"],
  MEDICAL_BOARD: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "DIAGNOSIS_VIEW", "RESULT_VIEW", "AUDIT_VIEW"],
  DEPARTMENT_HEAD: ["PATIENT_VIEW", "PATIENT_UPDATE", "ENCOUNTER_VIEW", "ENCOUNTER_CREATE",
    "CLINICAL_NOTE_CREATE", "CLINICAL_NOTE_UPDATE", "DIAGNOSIS_VIEW", "DIAGNOSIS_UPDATE",
    "ORDER_CREATE", "RESULT_VIEW", "RESULT_VERIFY", "PRESCRIPTION_CREATE", "PRESCRIPTION_APPROVE",
    "RESOURCE_VIEW", "RESOURCE_REQUEST", "RESOURCE_APPROVE", "BILL_VIEW",
    "SOS_VIEW", "SOS_UPDATE", "SCHEDULE_VIEW", "SCHEDULE_MANAGE", "BHYT_VIEW", "BHYT_VERIFY",
    "CAPACITY_VIEW", "CAPACITY_MANAGE"],
  DEPUTY_HEAD: ["PATIENT_VIEW", "PATIENT_UPDATE", "ENCOUNTER_VIEW", "ENCOUNTER_CREATE",
    "CLINICAL_NOTE_CREATE", "DIAGNOSIS_VIEW", "ORDER_CREATE", "RESULT_VIEW",
    "PRESCRIPTION_CREATE", "RESOURCE_VIEW", "RESOURCE_REQUEST", "BILL_VIEW",
    "SOS_VIEW", "SCHEDULE_VIEW", "SCHEDULE_MANAGE", "BHYT_VIEW", "CAPACITY_VIEW"],
  DOCTOR: ["PATIENT_VIEW", "PATIENT_UPDATE", "ENCOUNTER_VIEW", "ENCOUNTER_CREATE",
    "CLINICAL_NOTE_CREATE", "CLINICAL_NOTE_UPDATE", "DIAGNOSIS_VIEW", "DIAGNOSIS_UPDATE",
    "ORDER_CREATE", "RESULT_VIEW", "PRESCRIPTION_CREATE",
    "RESOURCE_VIEW", "RESOURCE_REQUEST", "BILL_VIEW",
    "SOS_VIEW", "SOS_UPDATE", "SCHEDULE_VIEW", "SCHEDULE_MANAGE", "BHYT_VIEW", "CAPACITY_VIEW", "HEALTH_DATA_VIEW"],
  NURSE: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "CLINICAL_NOTE_CREATE", "DIAGNOSIS_VIEW",
    "RESULT_VIEW", "RESOURCE_VIEW", "BILL_VIEW",
    "SOS_VIEW", "SOS_UPDATE", "SCHEDULE_VIEW", "BHYT_VIEW", "CAPACITY_VIEW", "HEALTH_DATA_VIEW"],
  TECHNICIAN: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "ORDER_CREATE", "RESULT_VIEW",
    "RESOURCE_VIEW", "SCHEDULE_VIEW", "SOS_VIEW", "CAPACITY_VIEW"],
  PHARMACIST: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "RESULT_VIEW", "PRESCRIPTION_CREATE",
    "PRESCRIPTION_APPROVE", "RESOURCE_VIEW", "RESOURCE_CREATE", "RESOURCE_UPDATE", "RESOURCE_REQUEST", "RESOURCE_ISSUE",
    "BILL_VIEW", "SCHEDULE_VIEW", "SOS_VIEW"],
  HR_MANAGER: ["USER_CREATE", "SCHEDULE_VIEW", "SCHEDULE_MANAGE", "AUDIT_VIEW", "DOCUMENT_APPROVE"],
  HR_STAFF: ["SCHEDULE_VIEW"],
  FINANCE_MANAGER: ["BILL_VIEW", "PAYMENT_CREATE", "PAYMENT_VERIFY", "REFUND_APPROVE",
    "AUDIT_VIEW", "BHYT_VIEW", "BHYT_VERIFY"],
  FINANCE_STAFF: ["BILL_VIEW", "PAYMENT_CREATE", "BHYT_VIEW", "BHYT_VERIFY"],
  IT_ADMIN: ["USER_CREATE", "ROLE_ASSIGN", "PERMISSION_ASSIGN", "AUDIT_VIEW",
    "RESOURCE_VIEW", "CAPACITY_VIEW", "ANOMALY_VIEW", "SCHEDULE_VIEW"],
  IT_STAFF: ["CAPACITY_VIEW", "ANOMALY_VIEW", "SCHEDULE_VIEW"],
  EMR_ADMIN: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "AUDIT_VIEW", "ANOMALY_VIEW"],
  REVIEW_OFFICER: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "RESULT_VIEW", "AUDIT_VIEW",
    "ANOMALY_VIEW", "ANOMALY_REVIEW"],
  QUALITY_MANAGER: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "RESULT_VIEW", "AUDIT_VIEW",
    "ANOMALY_VIEW", "ANOMALY_REVIEW", "CAPACITY_VIEW"],
  COMMAND_OPERATOR: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "RESOURCE_VIEW", "SOS_VIEW", "SOS_UPDATE",
    "SCHEDULE_VIEW", "CAPACITY_VIEW", "ANOMALY_VIEW", "AUDIT_VIEW"],
  DATA_ANALYST: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "RESULT_VIEW", "BILL_VIEW", "AUDIT_VIEW", "CAPACITY_VIEW"],
  FUNCTIONAL_MANAGER: ["RESOURCE_VIEW", "RESOURCE_CREATE", "RESOURCE_UPDATE", "RESOURCE_REQUEST", "DOCUMENT_CREATE", "DOCUMENT_PROCESS",
    "SCHEDULE_VIEW", "SCHEDULE_MANAGE", "BILL_VIEW", "AUDIT_VIEW"],
  ADMIN_STAFF: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "ENCOUNTER_CREATE", "DOCUMENT_CREATE",
    "DOCUMENT_RECEIVE", "SCHEDULE_VIEW", "BHYT_VIEW", "BHYT_VERIFY", "SOS_VIEW"],
  SUPPORT_STAFF: ["SCHEDULE_VIEW", "RESOURCE_VIEW", "SOS_VIEW"],
  BUILDING_MANAGER: ["RESOURCE_VIEW", "CAPACITY_VIEW", "SCHEDULE_VIEW", "SOS_VIEW", "AUDIT_VIEW"],
  SUPER_ADMIN: ["USER_CREATE", "ROLE_ASSIGN", "PERMISSION_ASSIGN", "AUDIT_VIEW",
    "RESOURCE_VIEW", "CAPACITY_VIEW", "ANOMALY_VIEW", "SCHEDULE_VIEW"],
  // Patient/Caregiver: chỉ dữ liệu của mình — enforce riêng theo từng route (scope=self)
  // PATIENT_VIEW/ENCOUNTER_VIEW ở đây LUÔN đi kèm scope=self hoặc grant hợp lệ.
  PATIENT: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "SCHEDULE_VIEW", "BHYT_VIEW"],
  CAREGIVER: ["PATIENT_VIEW", "ENCOUNTER_VIEW", "SCHEDULE_VIEW", "BHYT_VIEW"],
};

/** effective roles từ claims (legacy role + hospitalRole mới). */
function rolesOf(claims = {}) {
  return [claims.role, claims.hospitalRole].filter(Boolean);
}
/** user (claims) có quyền PERM mới không?
 * API mới enforce taxonomy mới nghiêm: nếu có hospitalRole thì CHỈ xét
 * hospitalRole (legacy CEO/DOCTOR/... chỉ để tương thích API cũ). */
function can(claims, perm) {
  const hrs = [claims && claims.hospitalRole].filter(Boolean);
  const eff = hrs.length ? hrs : rolesOf(claims);
  for (const r of eff) {
    if ((ROLE_PERMS2[r] || []).includes(perm)) return true;
  }
  return false;
}
function permsOf(claims) {
  const hrs = [claims && claims.hospitalRole].filter(Boolean);
  const eff = hrs.length ? hrs : rolesOf(claims);
  const s = new Set();
  for (const r of eff) for (const p of ROLE_PERMS2[r] || []) s.add(p);
  return [...s];
}

module.exports = { CLINICAL, RESOURCE, FINANCE, ADMIN_DOC, SYSTEM, CARE_OPS, ALL, ROLE_PERMS2, rolesOf, can, permsOf };
